In [18]:
import numpy as np

def sym(*args):
    sym_diff = np.array([], dtype=int)
    
    for indx, arr in enumerate(args):
        try:
            b = np.array(args[indx+1], dtype=int)
        except IndexError:
            continue

        if indx == 0:
            sym_diff = np.setxor1d(arr, b)
        else:
            sym_diff = np.setxor1d(sym_diff, b)
                
    return sym_diff

In [19]:
# sym([1, 2, 3], [5, 2, 1, 4]) should return [3, 4, 5].
sym([1,2,3], [5,2,1,4])

array([3, 4, 5])

In [20]:
# sym([1, 2, 3, 3], [5, 2, 1, 4]) should return [3, 4, 5].
sym([1, 2, 3, 3], [5, 2, 1, 4])

array([3, 4, 5])

In [21]:
# sym([1, 2, 3], [5, 2, 1, 4, 5]) should return [3, 4, 5].
sym([1, 2, 3], [5, 2, 1, 4, 5])

array([3, 4, 5])

In [22]:
# sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5]
sym([1, 2, 5], [2, 3, 5], [3, 4, 5])

array([1, 4, 5])

In [23]:
# sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]) should return [1, 4, 5].
sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5])

array([1, 4, 5])

In [24]:
# sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3]) should return [2, 3, 4, 6, 7].
sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3])

array([2, 3, 4, 6, 7])

In [25]:
# sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3], [5, 3, 9, 8], [1]) should return [1, 2, 4, 5, 6, 7, 8, 9].
sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3], [5, 3, 9, 8], [1])

array([1, 2, 4, 5, 6, 7, 8, 9])