In [ ]:
import numpy as np

In [17]:
I = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

In [5]:
A - B

array([[ 1, -2, -1],
       [ 1, -2,  3],
       [ 4, -1,  3]])

In [8]:
np.dot(A, B)

array([[-2,  8, -1],
       [-6, 18, -6],
       [ 1, 11, 11]])

In [11]:
AC =  np.dot(A, C)

In [12]:
BC = np.dot(B, C)

In [14]:
AC - BC

array([[-9,  2, -4,  0],
       [ 3, -2, 12,  4],
       [13,  1, 19, 14]])

In [15]:
np.dot(A, BC)

array([[ 25,  -1,   0,   1],
       [ 42,   0, -18,  -6],
       [ 79, -10,  57,  25]])

In [18]:
np.dot(C, D)

array([[8],
       [6],
       [7]])