In [1]:
import numpy as np

In [9]:
A = np.array([
    [1, -1],
    [2, 3]
])
B = np.array([
    [0, 1],
    [3, -5]
])
C = np.array([
    [0, 1, -1],
    [3, -2, 2]
])

In [16]:
AB = np.dot(A, B)
AB

array([[ -3,   6],
       [  9, -13]])

In [18]:
BC = np.dot(B, C)
BC

array([[  3,  -2,   2],
       [-15,  13, -13]])

In [19]:
np.dot(A, BC)

array([[ 18, -15,  15],
       [-39,  35, -35]])